# Generated by Django 3.0 on 2022-10-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(max_length=200)),
                ('produccion', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=200)),
                ('peso', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=200)),
                ('obs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('CI', models.CharField(max_length=200)),
                ('Establecimiento', models.CharField(max_length=200)),
                ('RUC', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('establecimiento', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.Animal')),
            ],
        ),
    ]
